- name: Build and push Docker images
  uses: docker/build-push-action@v1.1.0
  with:
    username: "${{ secrets.DOCKER_USERNAME }}"
    password: "${{ secrets.DOCKER_PASSWORD }}"
    repository: "crs4/regate"
    tags: latest
    # Automatically tags the built image with the git reference as per the readme
    tag_with_ref: true
    # Automatically tags the built image with the git short SHA as per the readme
    tag_with_sha: true
    # Comma-delimited list of labels to add to the built image
    labels: "title=regate"
    # Adds labels with git repository information to the built image
    add_git_labels: true
